Add new attribute 'supported' in pyproject.toml
beeware/briefcase-template pull request #24
Opened 2020-12-15 03:03 UTC by qlchan24

### Changes:
Add additional metadata attribute `supported = false` in the `pyproject.toml` for ios and android if the GUI framework is PySide2 or PPB.

Formattting of the toml file generated with Briefcase `new` command with Pyside2 selected:
![gui_pyside2](https://user-images.githubusercontent.com/65329090/102159865-56bf8600-3ebf-11eb-8ff8-08a93a6ee9e9.png)

Formattting of the toml file generated with Briefcase `new` command with Toga selected:
![gui_toga](https://user-images.githubusercontent.com/65329090/102160024-a1d99900-3ebf-11eb-9949-4115f3ee7ff1.png)

## Problem solved:

Ensures that the `pyproject.toml` file generated from this template using the briefcase `new` command will contain a flag to disallow creation of mobile apps with unsupported GUI through the briefcase `create` or `update` command. More details provided in the related issue below.

## Related issue:
Briefcase issue #539: [Provide better warnings when an app *can't* be deployed to mobile platforms](https://github.com/beeware/briefcase/issues/539)

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2020-12-15 07:53 UTC, freakboy3742 requested changes
This looks really good; The one suggestion I have is that for the cases where `supported=False`, there's no point including a requires block as well. As Toga is the only platform that realistically supports iOS and Android at present, I think it's fine to say `if toga: ... else: supported=False`

2020-12-17 10:46 UTC, qlchan24 commented
Thank you. I have changed the conditional tags as suggested and tested it out for the latest commit.

2020-12-17 11:03 UTC, freakboy3742 approved these changes
👍 Looks great! I'll merge this change at the same time I merge the related Briefcase PR.

2020-12-22 01:02 UTC, freakboy3742 commented
Correction - I'll need to wait until the next formal Briefcase release before merging. We're due for a new release - I'll aim to do this around the new year.

2020-12-22 02:26 UTC, qlchan24 commented
Sure, thanks for the update!

2022-02-25 09:13 UTC, freakboy3742 commented
My sincere apologies - Briefcase *did* receive a release in early 2021, but I forgot to I completely forgot to merge this PR. Better late than never? 😬

2022-02-25 09:13 UTC, merged