Loosen version requirement for PySide6
beeware/briefcase-template pull request #53
Opened 2023-02-13 19:04 UTC by rmartin16

## Changes
The PySide6 requirement of `~=6.2.4` is too strict since it only allows `pip` to install versions of PySide6 that match `6.2.*`. The intention is to allow installing `6.2.4` on certain platforms (notably Ubuntu 1804) while allowing the most recent to be installed where possible.

Using `PySide6~=6.2` achieves this. It would probably be ideal if we could tell `pip` "install the latest version `6.4.*` if any of them are supported or just install `6.2.4`"....but I couldn't figure out a way to do this.

## Dependent PRs
- beeware/.github#12
- beeware/.github#13

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2023-02-13 19:19 UTC, rmartin16 commented
Also curious....why does CI only build Flatpaks for `toga`?

2023-02-14 00:02 UTC, freakboy3742 requested changes
This all looks good; I've merged the .github change, so once this is updated it should be good to land.

2023-02-14 00:06 UTC, rmartin16 commented
I just remembered why I didn't convert this repo to use the `.github` workflow. When this CI for this repo runs `briefcase create`, it passes `--template`.

```
    - name: Create App
      run: |
        cd tests/apps
        cat verify-${{ matrix.framework }}.config | briefcase new --template ../../
```
I'll need to add that as an input back in `.github`.

2023-02-14 02:52 UTC, freakboy3742 approved these changes
👍

2023-02-14 02:52 UTC, merged