Generalize template for GUI framework plugins
beeware/briefcase-template pull request #82
Opened 2023-11-09 21:30 UTC by rmartin16

## Changes
- Generalizes the template to support arbitrary GUI frameworks
- RE: https://github.com/beeware/briefcase/pull/1524

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

2023-11-13 06:12 UTC, freakboy3742 requested changes
Mostly straightforward stuff, subject to the changes in the matching Briefcase PR. Only major issue is about testing strategy; details inline.

2023-11-13 06:12 UTC, freakboy3742 commented on tests/test_app_template.py
I'm not sure this test is validating what it once did. Previously, it was a check that the code generated by the template was actually valid, and passes flake8; however, now, it's doing those checks mostly on values that have been provided by the test itself. All the interesting logic that needs validation is in the Briefcase repo now. 

A `briefcase new --noinput && briefcase build` check is probably called for to ensure the template is actually valid and results in compilable content; but beyond that, the place we need to test this is in Briefcase.

2023-11-13 16:07 UTC, rmartin16 commented on requirements.txt
> +tox ==4.11.3
I was inspired by the way that these constraints are interpreted by the packaging infrastructure such that the operator is really a part of the version.
```python
>>> from packaging.requirements import Requirement
>>> str(Requirement("toga == 0.4.0").specifier)
'==0.4.0'
>>> str(Requirement("toga >= 0.4.0, <= 1").specifier)
'<=1,>=0.4.0'
```
But I should make them consistent with the rest of our dependency specifications.

2023-11-13 16:13 UTC, rmartin16 commented on tests/test_app_template.py
Yeah; that's something I've been struggling with for these changes. I have a similar [comment](https://github.com/beeware/briefcase/pull/1524#discussion_r1390314239) in https://github.com/beeware/briefcase/pull/1524.

I think the tests here are still relevant as-is, though....since the template itself does have some control over creating a valid project....as I've learned by having to seemingly endlessly tweak the jinja2 templating to play nicely.

We can consider the broader testing strategy in https://github.com/beeware/briefcase/pull/1524.

2023-11-17 05:57 UTC, freakboy3742 requested changes
One error found in the template, but otherwise this looks good to go once the repo reference is updated.

2023-11-17 05:57 UTC, freakboy3742 commented on {{ cookiecutter.app_name }}/pyproject.toml
> +{% if cookiecutter.pyproject_table_macOS or cookiecutter.pyproject_table_android %}
Should this be iOS, not macOS?

2023-11-17 06:51 UTC, rmartin16 commented on {{ cookiecutter.app_name }}/pyproject.toml
> +{% if cookiecutter.pyproject_table_macOS or cookiecutter.pyproject_table_android %}
Yep; thought I got em all. Thanks.

2023-11-17 07:28 UTC, freakboy3742 approved these changes
Marking as approved, conditional on changes that are needed as part of the [beeware/briefcase#1524 landing strategy](https://github.com/beeware/briefcase/pull/1524#pullrequestreview-1736118477)

2023-11-18 00:55 UTC, freakboy3742 approved these changes
Approved for final ship

2023-11-18 00:55 UTC, merged